name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify:
    uses: smnandre/.github/.github/workflows/Swift.yml@73b564c9b3e173df776fc88a630d7ec524d30b77
    with:
      runner: macos-26
